export const CREATE_POST = 'POST/CREATE_POST';

export const SAVE_PROJECT = 'GRAF/SAVE_PROJECT';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const GET_TOKEN = 'AUTH/GET_TOKEN';

export const UPDATE_ELEMENT = 'GRAF/UPDATE_ELEMENT'
export const CREATE_ELEMENT = 'GRAF/CREATE_ELEMENT'

